import type { Comment, Market } from "./types";

const DAY = 86_400_000;
const now = Date.UTC(2026, 8, 21, 16, 0, 0);

function ago(hours: number) {
  return now - hours * 3_600_000;
}

function c(user: string, text: string, hoursAgo: number, outcomeId?: string): Comment {
  return { id: `${user}-${hoursAgo}`, user, text, at: ago(hoursAgo), outcomeId };
}

export const MARKETS: Market[] = [
  {
    id: "ventra-launch",
    slug: "ventra-deploy-arbitrum-oct-2026",
    title: "Will $VENTRA deploy on Arbitrum One by October 31?",
    description:
      "Ventran is an Arbitrum One rewards token for wallets that already use the chain. This market resolves to Yes if the official $VENTRA ERC-20 is deployed on Arbitrum One and the contract address is published on ventran.xyz or @Ventranxyz on or before 31 Oct 2026, 23:59 UTC.",
    resolution:
      "Yes if a verified $VENTRA contract is live on Arbitrum One by the deadline, announced by the official site or @Ventranxyz. Pre-launch copycats do not count.",
    category: "arbitrum",
    tags: ["arbitrum", "crypto", "trending"],
    image: "/markets/arbitrum.jpg",
    endDate: "2026-10-31T23:59:00.000Z",
    featured: true,
    isNew: true,
    eventId: "ventra",
    eventTitle: "$VENTRA launch path",
    rowLabel: "Deploy by Oct 31",
    topics: ["ventra", "arbitrum"],
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.72, no: 0.28 },
    seedVolume: 2_840_000,
    liquidity: 410_000,
    comments: [
      c("arbmax", "Whitelist is already live. This is trading like a done deal.", 4, "yes"),
      c("nocontract", "Contract isn't deployed. Anything circulating now is fake — they said so.", 7, "no"),
      c("l2native", "2.8B to historical Arbitrum txs is a serious distribution. Watching the snapshot.", 11),
    ],
  },
  {
    id: "ventra-fdv",
    slug: "ventra-fdv-100m-first-week",
    title: "Will $VENTRA first-week FDV exceed $100 million?",
    description:
      "Fixed 10B supply. Resolves Yes if fully diluted valuation, using the highest Dexscreener/Arbiscan spot close in the first 7 days after pair creation, is at or above $100M.",
    resolution: "FDV = 10,000,000,000 × spot price. First 168 hours after official pair creation.",
    category: "crypto",
    tags: ["crypto", "arbitrum", "trending"],
    image: "/markets/trading.jpg",
    endDate: "2026-11-14T23:59:00.000Z",
    featured: true,
    isNew: true,
    eventId: "ventra",
    eventTitle: "$VENTRA launch path",
    rowLabel: "First-week FDV $100m",
    topics: ["ventra"],
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.34, no: 0.66 },
    seedVolume: 1_620_000,
    liquidity: 290_000,
    comments: [
      c("fdvarb", "4.5B in the launch pool is real depth. $100m FDV is 1¢/token. Doable.", 6, "yes"),
      c("fairdrop", "Airdrop size is huge. Float will crush a thin listing.", 9, "no"),
    ],
  },
  {
    id: "btc-150k",
    slug: "bitcoin-above-150k-eoy-2026",
    title: "Will Bitcoin close 2026 above $150,000?",
    description:
      "Resolves to Yes if the Binance BTCUSDT daily close on 31 Dec 2026 is at or above 150,000 USDT.",
    resolution: "Binance BTCUSDT 1D close, 31 Dec 2026 00:00 UTC candle close.",
    category: "crypto",
    tags: ["crypto", "finance", "trending"],
    image: "/markets/bitcoin.jpg",
    endDate: "2026-12-31T23:59:00.000Z",
    featured: true,
    topics: ["btc"],
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.41, no: 0.59 },
    seedVolume: 18_400_000,
    liquidity: 2_100_000,
    comments: [
      c("cycle", "Post-halving year. $150k is the consensus target, which usually means we miss it.", 14, "no"),
      c("spotetf", "ETF bid does not care about your cycle charts.", 18, "yes"),
    ],
  },
  {
    id: "fed-cut-oct",
    slug: "fed-rate-cut-october-2026",
    title: "Will the Fed cut rates at the October 2026 meeting?",
    description:
      "Resolves Yes if the FOMC lowers the federal funds target range at its scheduled October 2026 meeting.",
    resolution: "Official FOMC statement. A hold or hike is No. Emergency inter-meeting cuts do not count.",
    category: "finance",
    tags: ["finance", "politics", "trending"],
    image: "/markets/fed.jpg",
    endDate: "2026-10-29T20:00:00.000Z",
    featured: true,
    topics: ["fed"],
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.63, no: 0.37 },
    seedVolume: 9_720_000,
    liquidity: 1_350_000,
    comments: [
      c("rates", "Labor is cooling. October is live.", 3, "yes"),
      c("hawk", "They already cut twice. Pause is the base case if CPI sticks.", 8, "no"),
    ],
  },
  {
    id: "arb-tvl",
    slug: "arbitrum-number-one-l2-eoy-2026",
    title: "Will Arbitrum be the #1 Ethereum L2 by TVL at year end?",
    description:
      "Resolves Yes if Arbitrum One (+ Nova excluded) ranks first among Ethereum L2s by DefiLlama TVL at 31 Dec 2026 23:59 UTC. Base, OP Mainnet, Starknet, zkSync, Scroll, Linea, Blast compete.",
    resolution: "DefiLlama ‘Ethereum L2’ TVL ranking, excluding sidechains and L1s.",
    category: "arbitrum",
    tags: ["arbitrum", "crypto", "trending"],
    image: "/markets/arbitrum.jpg",
    endDate: "2026-12-31T23:59:00.000Z",
    featured: true,
    topics: ["arbitrum"],
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.58, no: 0.42 },
    seedVolume: 3_110_000,
    liquidity: 520_000,
    comments: [
      c("based", "Base is eating consumer flow. TVL lead is not guaranteed.", 5, "no"),
      c("oranges", "Orbit chains + native USDC still compound on Arbitrum.", 12, "yes"),
    ],
  },
  {
    id: "ventra-binance",
    slug: "ventra-binance-spot-90-days",
    title: "Will $VENTRA list on Binance Spot within 90 days of launch?",
    description:
      "Yes if a VENTRA/USDT or VENTRA/USDC Spot pair is open on Binance.com within 90 days of official pair creation on Arbitrum.",
    resolution: "Binance announcements or the Spot markets page. Binance Alpha / futures-only is No.",
    category: "crypto",
    tags: ["crypto", "arbitrum", "new"],
    image: "/markets/trading.jpg",
    endDate: "2027-01-31T23:59:00.000Z",
    isNew: true,
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.22, no: 0.78 },
    seedVolume: 940_000,
    liquidity: 180_000,
    comments: [c("listings", "90 days is aggressive for a new Arbitrum ticker.", 2, "no")],
  },
  {
    id: "ventra-nft",
    slug: "ventran-nft-sellout-24h",
    title: "Will the Ventran 10,000 NFT collection sell out in 24 hours?",
    description:
      "10,000 supply, FCFS, mint TBA. 1.2B $VENTRA reserved for holders. Resolves Yes if the collection reports 10,000 minted within 24 hours of public mint open.",
    resolution: "Official mint contract on Arbitrum. Whitelist-only phase does not start the clock; public FCFS does.",
    category: "arbitrum",
    tags: ["arbitrum", "crypto", "culture", "new"],
    image: "/markets/nft.jpg",
    endDate: "2026-12-15T23:59:00.000Z",
    isNew: true,
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.47, no: 0.53 },
    seedVolume: 780_000,
    liquidity: 160_000,
    comments: [c("pfp", "Allocation per NFT is the whole game. Price TBA is the risk.", 15)],
  },
  {
    id: "eth-8k",
    slug: "eth-above-8000-eoy-2026",
    title: "Will Ether close 2026 above $8,000?",
    description: "Yes if Binance ETHUSDT daily close on 31 Dec 2026 is ≥ 8,000 USDT.",
    resolution: "Binance ETHUSDT 1D close on 31 Dec 2026.",
    category: "crypto",
    tags: ["crypto", "finance"],
    image: "/markets/arbitrum.jpg",
    endDate: "2026-12-31T23:59:00.000Z",
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.29, no: 0.71 },
    seedVolume: 6_440_000,
    liquidity: 880_000,
    comments: [c("uwu", "$8k needs a full risk-on year. Possible, not priced.", 20, "no")],
  },
  {
    id: "house-2026",
    slug: "gop-wins-house-2026",
    title: "Will Republicans win the U.S. House in 2026?",
    description:
      "Resolves Yes if the Republican Party holds a majority of seated House members when the 120th Congress convenes in January 2027.",
    resolution: "AP or House Clerk party totals on opening day. Ties / vacancies seated later do not flip a Yes.",
    category: "politics",
    tags: ["politics", "trending"],
    image: "/markets/capitol.jpg",
    endDate: "2026-11-04T06:00:00.000Z",
    featured: true,
    eventId: "midterms-2026",
    eventTitle: "Who controls Congress after 2026?",
    rowLabel: "House",
    topics: ["politics"],
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.54, no: 0.46 },
    seedVolume: 24_800_000,
    liquidity: 3_200_000,
    comments: [
      c("midterms", "Historical midterm swing is real. Map is still a toss-up.", 10),
      c("generic", "Generic ballot has been inside the margin for eight weeks.", 16),
    ],
  },
  {
    id: "senate-2026",
    slug: "gop-holds-senate-2026",
    title: "Will Republicans hold the U.S. Senate after 2026?",
    description: "Yes if Republicans control 51 or more Senate seats at the start of the 120th Congress.",
    resolution: "Senate.gov party division, January 2027.",
    category: "politics",
    tags: ["politics"],
    image: "/markets/capitol.jpg",
    endDate: "2026-11-04T06:00:00.000Z",
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.61, no: 0.39 },
    seedVolume: 11_200_000,
    liquidity: 1_540_000,
    comments: [c("map", "Map favors the GOP. A wave is the only path the other way.", 22, "yes")],
    eventId: "midterms-2026",
    eventTitle: "Who controls Congress after 2026?",
    rowLabel: "Senate",
    topics: ["politics"],
  },
  {
    id: "l2-leader",
    slug: "top-ethereum-l2-eoy-2026",
    title: "Which Ethereum L2 leads TVL at the end of 2026?",
    description: "Categorical market on DefiLlama TVL leadership among Ethereum L2s on 31 Dec 2026.",
    resolution: "DefiLlama L2 TVL. ‘Other’ is any chain that is not Arbitrum, Base, or OP Mainnet.",
    category: "arbitrum",
    tags: ["arbitrum", "crypto"],
    image: "/markets/orbit.jpg",
    endDate: "2026-12-31T23:59:00.000Z",
    outcomes: [
      { id: "arb", label: "Arbitrum" },
      { id: "base", label: "Base" },
      { id: "op", label: "OP Mainnet" },
      { id: "other", label: "Other" },
    ],
    seed: { arb: 0.46, base: 0.38, op: 0.09, other: 0.07 },
    seedVolume: 4_050_000,
    liquidity: 640_000,
    comments: [
      c("coinbase", "Base has distribution. Arbitrum has DeFi.", 6),
      c("orbit", "Orbit TVL does not always accrue to One.", 13),
    ],
  },
  {
    id: "spx-eoy",
    slug: "sp500-above-7000-eoy-2026",
    title: "Will the S&P 500 close 2026 above 7,000?",
    description: "Yes if the S&P 500 index official close on 31 Dec 2026 is at or above 7,000.00.",
    resolution: "S&P Dow Jones Indices official close.",
    category: "finance",
    tags: ["finance"],
    image: "/markets/trading.jpg",
    endDate: "2026-12-31T21:00:00.000Z",
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.48, no: 0.52 },
    seedVolume: 7_330_000,
    liquidity: 990_000,
    comments: [c("beta", "Soft landing path still has this in play.", 19, "yes")],
  },
  {
    id: "recession",
    slug: "us-recession-by-end-2026",
    title: "Will the U.S. be in a recession before 2027?",
    description:
      "Yes if NBER dates a recession with any month in 2026, announced on or before 30 Jun 2027.",
    resolution: "NBER Business Cycle Dating Committee. Later revisions count if posted by the deadline.",
    category: "finance",
    tags: ["finance", "world"],
    image: "/markets/fed.jpg",
    endDate: "2026-12-31T23:59:00.000Z",
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.18, no: 0.82 },
    seedVolume: 5_100_000,
    liquidity: 720_000,
    comments: [c("nber", "Unemployment would have to break higher from here.", 28, "no")],
  },
  {
    id: "super-bowl",
    slug: "super-bowl-lxi-nfc-wins",
    title: "Will the NFC win Super Bowl LXI?",
    description: "Yes if the NFC champion wins Super Bowl LXI in February 2027.",
    resolution: "Official NFL result. Vacated / postponed still uses the played championship game.",
    category: "sports",
    tags: ["sports"],
    image: "/markets/stadium.jpg",
    endDate: "2027-02-14T08:00:00.000Z",
    topics: ["nfl"],
    outcomes: [
      { id: "yes", label: "Yes · NFC", short: "NFC" },
      { id: "no", label: "No · AFC", short: "AFC" },
    ],
    seed: { yes: 0.49, no: 0.51 },
    seedVolume: 3_880_000,
    liquidity: 540_000,
    comments: [c("spread", "Open as a coin flip. Come back in January.", 30)],
  },
  {
    id: "nba-27",
    slug: "nba-champion-2027-conference",
    title: "Which conference wins the 2027 NBA title?",
    description: "Western or Eastern Conference champion of the 2026–27 NBA season.",
    resolution: "Official NBA Finals winner’s conference.",
    category: "sports",
    tags: ["sports"],
    image: "/markets/basketball.jpg",
    endDate: "2027-06-20T08:00:00.000Z",
    outcomes: [
      { id: "west", label: "Western Conference" },
      { id: "east", label: "Eastern Conference" },
    ],
    seed: { west: 0.67, east: 0.33 },
    seedVolume: 2_240_000,
    liquidity: 380_000,
    comments: [c("west", "Talent concentration still sits west of the Mississippi.", 26, "west")],
  },
  {
    id: "world-series",
    slug: "al-wins-world-series-2026",
    title: "Will the American League win the 2026 World Series?",
    description: "Yes if the AL pennant winner wins the 2026 Fall Classic.",
    resolution: "MLB official result.",
    category: "sports",
    tags: ["sports", "new"],
    image: "/markets/stadium.jpg",
    endDate: "2026-11-05T08:00:00.000Z",
    isNew: true,
    outcomes: [
      { id: "yes", label: "Yes · AL", short: "AL" },
      { id: "no", label: "No · NL", short: "NL" },
    ],
    seed: { yes: 0.52, no: 0.48 },
    seedVolume: 1_150_000,
    liquidity: 210_000,
    comments: [c("october", "Rotation depth is the whole series.", 1)],
  },
  {
    id: "ceasefire",
    slug: "ukraine-ceasefire-2026",
    title: "Will a Ukraine-Russia ceasefire be announced in 2026?",
    description:
      "Yes if both governments, or a joint statement via a mediating state, announce a ceasefire covering the full front that takes effect before 1 Jan 2027.",
    resolution: "A localized pause or humanitarian corridor is No. A full-front ceasefire of ≥ 72 hours is Yes.",
    category: "geopolitics",
    tags: ["geopolitics", "world"],
    image: "/markets/oil.jpg",
    endDate: "2026-12-31T23:59:00.000Z",
    topics: ["russia"],
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.31, no: 0.69 },
    seedVolume: 8_960_000,
    liquidity: 1_180_000,
    comments: [c("front", "Talks exist. A signed pause before January is still a long shot.", 21, "no")],
  },
  {
    id: "nato-clash-dec",
    slug: "nato-russia-clash-dec-2026",
    title: "Will NATO and Russia clash militarily by December 31?",
    description:
      "Yes if a direct kinetic engagement occurs between NATO-flagged forces and Russian Federation forces on or before 31 Dec 2026. Proxy-only fighting does not count.",
    resolution:
      "A confirmed exchange of fire involving NATO-assigned units and Russian units. Cyber or sanctions are No. Accidental airspace incidents under 24 hours with no casualties are No.",
    category: "geopolitics",
    tags: ["geopolitics", "world", "trending"],
    image: "/markets/nato.jpg",
    endDate: "2026-12-31T23:59:00.000Z",
    featured: true,
    isNew: true,
    eventId: "nato-russia",
    eventTitle: "NATO x Russia military clash by…?",
    rowLabel: "December 31",
    topics: ["russia"],
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.29, no: 0.71 },
    seedVolume: 7_100_000,
    liquidity: 980_000,
    comments: [
      c("front", "Year-end line is where the tail lives. Still a No unless Article 5 is tested.", 3, "no"),
    ],
  },
  {
    id: "nato-clash-oct",
    slug: "nato-russia-clash-oct-2026",
    title: "Will NATO and Russia clash militarily by October 31?",
    description:
      "Same clash definition as the December contract, with an October 31 deadline.",
    resolution: "Same as the December 31 NATO–Russia clash market, cut at 31 Oct 2026 23:59 UTC.",
    category: "geopolitics",
    tags: ["geopolitics", "world", "trending"],
    image: "/markets/nato.jpg",
    endDate: "2026-10-31T23:59:00.000Z",
    isNew: true,
    eventId: "nato-russia",
    eventTitle: "NATO x Russia military clash by…?",
    rowLabel: "October 31",
    topics: ["russia"],
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.17, no: 0.83 },
    seedVolume: 4_200_000,
    liquidity: 610_000,
    comments: [c("dates", "Six weeks is a very short window for a NATO-level incident.", 2, "no")],
  },
  {
    id: "oil-90",
    slug: "brent-above-90-eoy-2026",
    title: "Will Brent crude close 2026 above $90?",
    description: "Yes if the ICE Brent front-month settlement on 31 Dec 2026 is ≥ $90.00.",
    resolution: "ICE Brent settlement.",
    category: "geopolitics",
    tags: ["geopolitics", "finance"],
    image: "/markets/oil.jpg",
    endDate: "2026-12-31T23:59:00.000Z",
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.27, no: 0.73 },
    seedVolume: 2_010_000,
    liquidity: 340_000,
    comments: [c("opec", "Spare capacity is the ceiling unless a shock hits the Gulf.", 17, "no")],
  },
  {
    id: "apple-event",
    slug: "apple-folds-a-device-2026",
    title: "Will Apple announce a folding device in 2026?",
    description: "Yes if Apple announces a foldable iPhone, iPad, or Mac for sale during calendar 2026.",
    resolution: "Apple Newsroom or a keynote. Rumors, leaks, and patent filings are No.",
    category: "tech",
    tags: ["tech"],
    image: "/markets/device.jpg",
    endDate: "2026-12-31T23:59:00.000Z",
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.36, no: 0.64 },
    seedVolume: 1_770_000,
    liquidity: 300_000,
    comments: [c("supply", "Supply chain has folding panels. Apple is late on purpose.", 24)],
  },
  {
    id: "openai-ipo",
    slug: "openai-ipo-s1-2026",
    title: "Will OpenAI file an S-1 in 2026?",
    description: "Yes if OpenAI or a parent/successor files a Form S-1 (or F-1) with the SEC in 2026.",
    resolution: "SEC EDGAR filing. A tender offer or secondary sale is No.",
    category: "tech",
    tags: ["tech", "finance"],
    image: "/markets/device.jpg",
    endDate: "2026-12-31T23:59:00.000Z",
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.24, no: 0.76 },
    seedVolume: 4_620_000,
    liquidity: 710_000,
    comments: [c("cap", "They do not need public capital. Governance is the blocker.", 27, "no")],
  },
  {
    id: "best-picture",
    slug: "best-picture-favorite-oscars-2027",
    title: "Will a studio film win Best Picture at the 2027 Oscars?",
    description:
      "Yes if the Academy Award for Best Picture (99th) goes to a film whose primary theatrical distributor is a major or mini-major studio, not a streamer-first original.",
    resolution: "AMPAS winner. Streamer-financed films that had a qualifying theatrical run still count as streamer if that is the primary distributor.",
    category: "culture",
    tags: ["culture"],
    image: "/markets/cinema.jpg",
    endDate: "2027-03-15T07:00:00.000Z",
    outcomes: [
      { id: "yes", label: "Yes · studio", short: "Studio" },
      { id: "no", label: "No · streamer", short: "Streamer" },
    ],
    seed: { yes: 0.57, no: 0.43 },
    seedVolume: 640_000,
    liquidity: 120_000,
    comments: [c("campaign", "Theatrical still owns the campaign machine.", 33, "yes")],
  },
  {
    id: "starship",
    slug: "starship-catch-both-ends-2026",
    title: "Will SpaceX catch a Starship booster and ship in one 2026 flight?",
    description: "Yes if a single Starship flight in 2026 has both the booster and the ship caught at the towers.",
    resolution: "SpaceX or FAA/public video confirming dual catch on the same mission.",
    category: "tech",
    tags: ["tech", "world"],
    image: "/markets/orbit.jpg",
    endDate: "2026-12-31T23:59:00.000Z",
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.44, no: 0.56 },
    seedVolume: 2_560_000,
    liquidity: 430_000,
    comments: [c("tower", "Booster catches are routine. The ship is the remaining trick.", 29)],
  },
  {
    id: "uk-pm",
    slug: "uk-pm-still-in-office-eoy-2026",
    title: "Will the current UK Prime Minister still be in office at year end?",
    description: "Yes if the person holding the office of Prime Minister on 21 Sep 2026 is still PM on 31 Dec 2026.",
    resolution: "gov.uk. Resignation with a successor from the same party still counts as No if the person changed.",
    category: "world",
    tags: ["world", "politics"],
    image: "/markets/fed.jpg",
    endDate: "2026-12-31T23:59:00.000Z",
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.71, no: 0.29 },
    seedVolume: 1_980_000,
    liquidity: 360_000,
    comments: [c("westminster", "Three months is a short window unless something breaks.", 31, "yes")],
  },
  {
    id: "airdrop-size",
    slug: "ventra-median-airdrop-above-20k",
    title: "Will the median $VENTRA airdrop exceed 20,000 tokens?",
    description:
      "180 $VENTRA per Arbitrum One transaction, 2.8B allocated. Resolves Yes if the median allocation among submitted, eligible wallets is greater than 20,000 VENTRA.",
    resolution:
      "Official allocation dashboard or a verifiable Merkle dump. Empty / spam wallets excluded if the project publishes an eligibility filter.",
    category: "arbitrum",
    tags: ["arbitrum", "crypto", "new"],
    image: "/markets/nft.jpg",
    endDate: "2026-11-30T23:59:00.000Z",
    isNew: true,
    outcomes: [
      { id: "yes", label: "Yes", short: "Yes" },
      { id: "no", label: "No", short: "No" },
    ],
    seed: { yes: 0.39, no: 0.61 },
    seedVolume: 510_000,
    liquidity: 110_000,
    comments: [
      c("sybil", "Median gets crushed by one-tx farmers unless they filter hard.", 8, "no"),
      c("og", "Real Arbitrum users have hundreds of txs. 20k is only ~111 txs.", 9, "yes"),
    ],
  },
];

export const MARKET_BY_SLUG = Object.fromEntries(MARKETS.map((m) => [m.slug, m]));
export const MARKET_BY_ID = Object.fromEntries(MARKETS.map((m) => [m.id, m]));

export function isBinary(market: Market): boolean {
  return market.outcomes.length === 2 && market.outcomes.some((o) => o.id === "yes");
}

export const CATEGORY_LABEL: Record<string, string> = {
  trending: "Trending",
  new: "New",
  crypto: "Crypto",
  arbitrum: "Arbitrum",
  politics: "Politics",
  sports: "Sports",
  finance: "Finance",
  geopolitics: "Geopolitics",
  tech: "Tech",
  culture: "Culture",
  world: "World",
};

export const TICKER_ITEMS = [
  "Whitelist open — check your Arbitrum allocation on ventran.xyz",
  "$VENTRA · 10B fixed supply · no presale · no private round",
  "Live sports · Azuro book · USDT on Polygon",
  "2.8B $VENTRA to wallets that already used Arbitrum One",
  "Trade what’s next",
  "Desk markets stay paper USDC until they list on-chain",
];
