/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BreakingRouteImport } from './routes/breaking'
import { Route as CombosRouteImport } from './routes/combos'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LeadersRouteImport } from './routes/leaders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerpsRouteImport } from './routes/perps'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MarketSlugRouteImport } from './routes/market.$slug'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakingRoute = BreakingRouteImport.update({
  id: '/breaking',
  path: '/breaking',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersRoute = LeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerpsRoute = PerpsRouteImport.update({
  id: '/perps',
  path: '/perps',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketSlugRoute = MarketSlugRouteImport.update({
  id: '/market/$slug',
  path: '/market/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breaking': typeof BreakingRoute
  '/combos': typeof CombosRoute
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/leaders': typeof LeadersRoute
  '/login': typeof LoginRoute
  '/perps': typeof PerpsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/market/$slug': typeof MarketSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breaking': typeof BreakingRoute
  '/combos': typeof CombosRoute
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/leaders': typeof LeadersRoute
  '/login': typeof LoginRoute
  '/perps': typeof PerpsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/market/$slug': typeof MarketSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breaking': typeof BreakingRoute
  '/combos': typeof CombosRoute
  '/feed': typeof FeedRoute
  '/help': typeof HelpRoute
  '/leaders': typeof LeadersRoute
  '/login': typeof LoginRoute
  '/perps': typeof PerpsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/market/$slug': typeof MarketSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/breaking'
    | '/combos'
    | '/feed'
    | '/help'
    | '/leaders'
    | '/login'
    | '/perps'
    | '/portfolio'
    | '/profile'
    | '/rewards'
    | '/search'
    | '/market/$slug'
    | '/u/$handle'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/breaking'
    | '/combos'
    | '/feed'
    | '/help'
    | '/leaders'
    | '/login'
    | '/perps'
    | '/portfolio'
    | '/profile'
    | '/rewards'
    | '/search'
    | '/market/$slug'
    | '/u/$handle'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/breaking'
    | '/combos'
    | '/feed'
    | '/help'
    | '/leaders'
    | '/login'
    | '/perps'
    | '/portfolio'
    | '/profile'
    | '/rewards'
    | '/search'
    | '/market/$slug'
    | '/u/$handle'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreakingRoute: typeof BreakingRoute
  CombosRoute: typeof CombosRoute
  FeedRoute: typeof FeedRoute
  HelpRoute: typeof HelpRoute
  LeadersRoute: typeof LeadersRoute
  LoginRoute: typeof LoginRoute
  PerpsRoute: typeof PerpsRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  SearchRoute: typeof SearchRoute
  MarketSlugRoute: typeof MarketSlugRoute
  UHandleRoute: typeof UHandleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breaking': {
      id: '/breaking'
      path: '/breaking'
      fullPath: '/breaking'
      preLoaderRoute: typeof BreakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders': {
      id: '/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof LeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perps': {
      id: '/perps'
      path: '/perps'
      fullPath: '/perps'
      preLoaderRoute: typeof PerpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$slug': {
      id: '/market/$slug'
      path: '/market/$slug'
      fullPath: '/market/$slug'
      preLoaderRoute: typeof MarketSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreakingRoute: BreakingRoute,
  CombosRoute: CombosRoute,
  FeedRoute: FeedRoute,
  HelpRoute: HelpRoute,
  LeadersRoute: LeadersRoute,
  LoginRoute: LoginRoute,
  PerpsRoute: PerpsRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  SearchRoute: SearchRoute,
  MarketSlugRoute: MarketSlugRoute,
  UHandleRoute: UHandleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
